name: Build Debug APK
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build APK Debug
        run: ./gradlew assembleDebug
      - name: List APK files
        run: find app/build/outputs/apk/ -name "*.apk" -print
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rempang-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
